### ISSUE TITLE
运行时缺少文件

### ISSUE THREAD

**Issue by stakeswky** [wenhaomin/ChatGPT-PromptGenius#1]
你好，我尝试按照教程启动该网站，但是提示缺少app.json文件，请问我应该去哪里获取这份文件呢

**Comment by wenhaomin** [comment]
你好，感谢关注，这个应该是我们在最近的一版更新中漏掉了，近期更新的版本中我们会补上。

**Comment by Logan-Lin** [comment]
Hello there!
In the latest commit, we added the `app_config.json` file and the server should start with no problem. 
The `app_config.json` file claims database connection and we previously were afraid that it may contain sensitive contents, but this is not an issue now.
We also updated the readme file, briefly introduce the data model design.
