### ISSUE TITLE
master has error

### ISSUE THREAD

**Issue by mjpcasey** [wenhaomin/ChatGPT-PromptGenius#3]
![image](https://github.com/wenhaomin/ChatGPT-PromptGenius/assets/24688898/047424f7-54de-4f96-8052-010f046a1247)

start init , this code has err

**Comment by Logan-Lin** [comment]
Hi! In the lastest commit, we fix this bug. This error occurs during the database initialization, since previously we create the view before tables are created.
Please let us know if there are further problems.
