### ISSUE TITLE
chrome 浏览器复制Prompt功能 不起作用

### ISSUE THREAD

**Issue by tiancool** [wenhaomin/ChatGPT-PromptGenius#4]
不知道什么原因，chrome 浏览器复制Prompt功能 不起作用，请更新，需要手法复制才行，不方便。以为是插件影响，关了也不行。

**Comment by Logan-Lin** [comment]
你好，感谢关注本项目。
复制功能不起作用很可能是因为复制功能要求安全连接（https），在非localhost连接时走http协议，复制功能是不能正常工作的。
