### ISSUE TITLE
你好 admin的代码或者模板好像没有

### ISSUE THREAD

**Issue by liiijz** [wenhaomin/ChatGPT-PromptGenius#5]
你好 admin的代码或者模板好像没有 另外能否给个sql的初始数据文件

**Comment by wenhaomin** [comment]
你好，感谢关注本项目。关于admin的代码，出于对网站安全运营的考虑，目前我们暂时没有开源admin代码的打算。
关于sql的初始数据文件，其实在运行当前的code之后，就会自动生成一个db文件，里面会有多个初始化好的sql表，你可以通过数据库管理工具直接打开，然后往里面添加数据。
