### ISSUE TITLE
Feature Request 能否提供docker部署方式

### ISSUE THREAD

**Issue by ChenjieXu** [wenhaomin/ChatGPT-PromptGenius#6]
开发者你们好，你们的工作真的让人眼前一亮。在部署的时候，在我的服务器上裸机部署很麻烦，是否能提供docker的部署方式。

**Comment by wenhaomin** [comment]
你好，感谢对我们工作的认可和提供宝贵的建议，之后我们会考虑加入docker的部署方式，再次感谢
