### ISSUE TITLE
good job

### ISSUE THREAD

**Issue by chaiyuan2046** [wenhaomin/ChatGPT-PromptGenius#7]
such a cool project.
but nothing except static png was show when i start the project
uum,could you share some sample data in PromptGenius.db? tks

**Comment by Logan-Lin** [comment]
Thank you for your appreciations!
We will provide a sample database file in a future commit.

**Comment by chaiyuan2046** [comment]
so excited~

**Comment by Logan-Lin** [comment]
Hi! We've added a sample database in the latest commit. Feel free to try it out! If you encounter further problems please also let us know.
